version: "3"
services:
  mqtt:
    hostname: mqtt
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro    
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - frigate
    environment:
      - TZ=Asia/Ho_Chi_Minh

  frigate-machine-learning:
    hostname: ml_engine
    container_name: frigate_machine_learning
    image: frigate-machine-learning:latest
    # extends:
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference
    
    build:
      context: ./machine-learning
      dockerfile: Dockerfile
      args:
        - DEVICE=cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: "all" # 1
              device_ids: ['0'] # must comment the above line if this line is uncommented.
              capabilities: [gpu]    
    ports:
      - 3003:3003
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro    
      - ./machine-learning:/usr/src/app
      - ./models/.cache:/cache
    env_file:
      - ./machine-learning/.env
    environment:
      - TZ=Asia/Ho_Chi_Minh    
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - frigate


  devcontainer:
    hostname: frigate
    container_name: frigate
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "1024mb"
    image: frigate:latest-tensorrt #ghcr.io/blakeblackshear/frigate:0.14.1-tensorrt #frigate:latest-tensorrt
    build:
      context: .
      dockerfile: docker/main/Dockerfile    #docker/tensorrt/Dockerfile.amd64   # docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer # to  build base image, need to uncommend this line
      # target: devcontainer-trt 
    ## Uncomment this block for nvidia gpu support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: "all" # 1
              device_ids: ['0'] # must comment the above line if this line is uncommented.
              capabilities: [gpu]
    # environment:
      # YOLO_MODELS: yolov7-320,yolov8l

    devices:
    - /dev/video0:/dev/video0
    - /dev/video1:/dev/video1
    - /dev/video2:/dev/video2  # webcam
    - /dev/dri:/dev/dri
    - /dev/dma_heap
    - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    # - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    # - /dev/video11:/dev/video11 # For Raspberry Pi 4B
    # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware    
    # - /dev/rga
    # - /dev/mpp_service      
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    environment:
      - FRIGATE_RTSP_PASSWORD=admin
      - TZ=Asia/Ho_Chi_Minh
      # - PATH=/usr/lib/ffmpeg/7.0/bin:/usr/lib/ffmpeg/6.0/bin:/usr/lib/ffmpeg/5.0/bin:/usr/local/bin:/usr/local/sbin:/usr/local/go2rtc:/usr/local/nginx/sbin:/usr/local/tempio/bin:${PATH}

    volumes:
      # - .:/workspace/frigate:cached
      # - ./web/dist:/opt/frigate/web:cached
      - /etc/timezone:/etc/timezone:ro      
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /dev/bus/usb:/dev/bus/usb
      - ./models:/models
      - ./storage:/media/frigate
      - ./frigate:/opt/frigate/frigate
      - ./videos:/videos

      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8556:8554" # RTSP feeds
      - "8555:8555/tcp" # M
      - "8555:8555/udp"
      - "5555:5555" # M      
      - "5001:5001" 
    networks:
      - frigate
 

networks:
  frigate:
    driver: bridge