web_port: 5000

mqtt:
  host: mqtt.blakeshome.com
  topic_prefix: cameras

cameras:
  back:
    rtsp:
      user: viewer
      host: 10.0.10.10
      port: 554
      password: $RTSP_PASSWORD
      path: /cam/realmonitor?channel=1&subtype=2
    regions:
      - size: 350
        x_offset: 0
        y_offset: 300
        min_person_size: 5000
      - size: 400
        x_offset: 350
        y_offset: 250
        min_person_size: 2000
      - size: 400
        x_offset: 750
        y_offset: 250
        min_person_size: 2000